[project]
name = "demo-fastapi-tls"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.4",
    "loguru>=0.7.2",
    "uvicorn>=0.32.0",
]
